### ISSUE TITLE
Using high_cpu_parser.py no longer seems to work

### ISSUE THREAD

**Issue by isuftin** [MicrosoftDocs/microsoft-365-docs#12524]
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/linux-support-perf?view=o365-worldwide suggests the following:

```sh
wget -c https://raw.githubusercontent.com/microsoft/mdatp-xplat/master/linux/diagnostic/high_cpu_parser.py
mdatp diagnostic real-time-protection-statistics --output json | python high_cpu_parser.py
```

When doing this, I am getting the following on a RHEL 8 instance:

```sh
mdatp diagnostic real-time-protection-statistics --output json | python high_cpu_parser.py | head
Traceback (most recent call last):
  File "high_cpu_parser.py", line 35, in <module>
    lines = sorted(vals, key=lambda k: int(k['total_files_scanned']), reverse=True)
  File "high_cpu_parser.py", line 35, in <lambda>
    lines = sorted(vals, key=lambda k: int(k['total_files_scanned']), reverse=True)
KeyError: 'total_files_scanned'
```

```sh
python --version

Python 3.6.8
```

```sh
 mdatp diagnostic real-time-protection-statistics --output json | jq '.counters[0:3]'
[
  {
    "id": 1,
    "isActive": true,
    "maxFileScanTime": "0",
    "name": "systemd",
    "path": "/usr/lib/systemd/systemd",
    "resourceScanTime": "0",
    "scannedFilePaths": null,
    "totalEventsSent": "0",
    "totalFilesScanned": "0",
    "totalScanTime": "0"
  },
  {
    "id": 590,
    "isActive": true,
    "maxFileScanTime": "0",
    "name": "systemd-journal",
    "path": "/usr/lib/systemd/systemd-journald",
    "resourceScanTime": "0",
    "scannedFilePaths": null,
    "totalEventsSent": "0",
    "totalFilesScanned": "0",
    "totalScanTime": "0"
  },
  {
    "id": 623,
    "isActive": true,
    "maxFileScanTime": "0",
    "name": "systemd-udevd",
    "path": "/usr/lib/systemd/systemd-udevd",
    "resourceScanTime": "0",
    "scannedFilePaths": null,
    "totalEventsSent": "0",
    "totalFilesScanned": "0",
    "totalScanTime": "0"
  }
]
```

**Comment by isuftin** [comment]
Editing the downloaed python file and changing every string instance of `total_files_scanned` to `totalFilesScanned` makes the python script work.

Looks like the output from `mdatp diagnostic real-time-protection-statistics --output json` has changed since the Python script was originally written :(

**Comment by yogkumgit** [comment]
@Dansimp Please help us in resolving this issue. Thanks

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
