### ISSUE TITLE
Cross-Tenant Migration

### ISSUE THREAD

**Issue by Srinivasu9900** [MicrosoftDocs/microsoft-365-docs#8264]
Followed the Link : https://docs.microsoft.com/en-us/microsoft-365/enterprise/cross-tenant-mailbox-migration?view=o365-worldwide

Error:

RunspaceId      : 82544190-f21e-47c7-9c52-acde07be0b28
Result          : Failed
Message         : Error finding certificate '' from azure key vault for tenant '8d5d10bb-a524-4e33-a768-f575eda8e303'.
SupportsCutover : False
ErrorDetail     : Microsoft.Exchange.MailboxReplicationService.KeyVaultFailureErrorException: Error finding certificate '' from azure key vault for tenant '8d5d10bb-a524-4e33-a768-f575eda8e303'. ---> 
                  Microsoft.Exchange.MailboxReplicationService.KeyVaultFailureException: Failed to retrieve secret from key vault for tenant: '8d5d10bb-a524-4e33-a768-f575eda8e303'. Original failure: 
                  'AggregateException: One or more errors occurred. ---> ArgumentNullException: Value cannot be null.
                  Parameter name: certificateIdentifier
                  ===
                     at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<GetCertificateAsync>d__21.MoveNext()
                  ===
                     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
                     at Microsoft.Exchange.MailboxReplicationService.AzureKeyVaultClient.RetrievePfxFromAzureKeyVaultAsExchange(String certificateIdentifier)
                  '
                     at Microsoft.Exchange.MailboxReplicationService.AzureKeyVaultClient.RetrievePfxFromAzureKeyVaultAsExchange(String certificateIdentifier)
                     at Microsoft.Exchange.MailboxReplicationService.CommonUtils.<>c__DisplayClass128_0.<GetCertificateViaAzureKeyVault>b__0(String s)
                     at Microsoft.Exchange.MailboxReplicationService.CommonUtils.LookupCertificateInCache(String certLookupKey, Func`2 certificateLookUpDelegate)
                     at Microsoft.Exchange.MailboxReplicationService.CommonUtils.GetCertificateViaAzureKeyVault(String akvOwnerTenantId, String resourceOwnerTenantId, String certificateIdentifier)
                     --- End of inner exception stack trace ---
                     at Microsoft.Exchange.MailboxReplicationService.CommonUtils.GetCertificateViaAzureKeyVault(String akvOwnerTenantId, String resourceOwnerTenantId, String certificateIdentifier)
                     at Microsoft.Exchange.MailboxReplicationService.OAuthAuthorizer.GetAppOnlyAccessTokenViaCertificate(String remoteHostName, String appOwnerTenant, String resourceOwnerTenant, String clientId, String 
                  certificateIdentifier, String incomingCertificateIdentifier, String resource)
                     at Microsoft.Exchange.MailboxReplicationService.OAuthAuthorizer.GetAppOnlyAccessToken(String remoteHostName, String appOwnerTenant, String resourceOwnerTenant, String clientId, String 
                  certificateIdentifier, String incomingCertificateIdentifier, String resource, NetworkCredential appCredential)
                     at Microsoft.Exchange.Migration.MigrationExchangeProxyRpcClient.VerifyOAuthInformation(String remoteHostName, Guid appOwnerTenantId, Guid resourceOwnerTenantId, String applicationId, String 
                  appSecretKeyVaultUrl, String resource, NetworkCredential appCredential, LocalizedException& error)
                     at Microsoft.Exchange.Migration.MigrationEndpointVerifier.VerifyConnectivity(MigrationEndpointBase endpoint)
                     at Microsoft.Exchange.Management.Migration.MigrationService.Endpoint.TestMigrationServerAvailability.InternalProcessEndpoint(Boolean fromAutoDiscover)
TestedEndpoint  : 
IsValid         : True
Identity        : 
ObjectState     : New

PS C:\Windows\system32>

**Comment by msbemba** [comment]
@Srinivasu9900 Thank you for your feedback and the error logs. Since this is a technical issue that requires troubleshooting, We request you to contact the support team via the Need help section on the admin center to help you fix this issue.

Hope this helps!

Thanks
Sri

**Comment by yogkumgit** [comment]
@msbemba Thank you very much for the contribution and sharing this explanation. @Srinivasu9900 Hope this comment is helpful for you. Considering the nature of the issue, as advised, please open a service ticket in your tenant and follow with them for the resolution. We proceed to close it as here we are limited to documentation fixes and improvements only.
We will be very happy if you can share the outcome or resolution with us if you see documentation update is required. We will certainly update this documentation with that valuable information. Thanks again, for taking out some time to open the issue. Appreciate and encourage you to do the same in future also.
