### ISSUE TITLE
Requirements for MSCommerce Module - PS Editions/Versions

### ISSUE THREAD

**Issue by TobiasKeitsch** [MicrosoftDocs/microsoft-365-docs#842]
It is not possible to use Powershell Core, due to System.Windows.Forms dependancy in the authentication method.
It would be good to either add possibility to use PS Core, or add in requirements what PSVersion is supported.

The following error occurs with PS v6.2.1
```
PS C:\WINDOWS\System32> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.1
PSEdition                      Core
GitCommitId                    6.2.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\WINDOWS\System32> Connect-MSCommerce                                                                              Connect-MSCommerce : Unable to establish connection
At line:1 char:1
+ Connect-MSCommerce
+ ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCommerce

PS C:\WINDOWS\System32> $Error[0] | select *

writeErrorStream      : True
PSMessageDetails      :
Exception             : Microsoft.PowerShell.Commands.WriteErrorException: Unable to establish connection
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Connect-MSCommerce
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Connect-MSCommerce, <DocumentPath>\PowerShell\Modules\MSCommerce\1.2\MSCommerce.psm1: line 96
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

In the function Connect-MSCommerce in <DocumentPath>\PowerShell\Modules\MSCommerce\1.2\MSCommerce.psm1: line 96 the following code is causing the problem:
```
    [string] $ClientId = "3d5cffa9-04da-4657-8cab-c7f074657cad"
    [Uri] $RedirectUri = [uri] "http://localhost/m365/commerce"
    [string] $Resource = "aeb86249-8ea3-49e2-900b-54cc8e308f85"   #LicenseManager App Id
  
$authorityUrl = "https://login.windows.net/common"
  $authCtx = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" $authorityUrl

  $platformParams = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters" ([Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior]::Always)

  $token = $authCtx.AcquireTokenAsync($Resource, $ClientId, $RedirectUri, $platformParams).Result

```

To find the error the last row needs to be edited to expose the error code:

``` 
PS C:\WINDOWS\System32> $authCtx.AcquireTokenAsync($Resource, $ClientId, $RedirectUri, $platformParams) | select *                                            
Result                  :
Id                      : 6
Exception               : System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Cu
                          lture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.) ---> System.IO.FileNotFoundException:
                          Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The syst
                          em cannot find the file specified.
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.WebUI.AcquireAuthorizationAsync(Uri authorizationUri, Uri r
                          edirectUri, RequestContext requestContext)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.AcquireAuthorizationAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.PreTokenRequestAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientI
                          d, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId, String extraQueryParameters, String claims)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, String clientId, Uri
                           redirectUri, IPlatformParameters parameters)
                             --- End of inner exception stack trace ---
                          ---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0,
                          Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
                          File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.WebUI.AcquireAuthorizationAsync(Uri authorizationUri, Uri r
                          edirectUri, RequestContext requestContext)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.AcquireAuthorizationAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.PreTokenRequestAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.RunAsync()
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenCommonAsync(String resource, String clientI
                          d, Uri redirectUri, IPlatformParameters parameters, UserIdentifier userId, String extraQueryParameters, String claims)
                             at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireTokenAsync(String resource, String clientId, Uri
                           redirectUri, IPlatformParameters parameters)

                          <---

Status                  : Faulted
IsCanceled              : False
IsCompleted             : True
IsCompletedSuccessfully : False
CreationOptions         : None
AsyncState              :
IsFaulted               : True
AsyncWaitHandle         : System.Threading.ManualResetEvent
CompletedSynchronously  : False

```

**Comment by mypil** [comment]
@TobiasKeitsch - May we know which Microsoft document link you used in reference to this issue?
Please share it with us so we can investigate further. Thank you.

**Comment by TobiasKeitsch** [comment]
Sorry, missed to add the link. Here it is:
https://docs.microsoft.com/en-gb/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell

**Comment by mypil** [comment]
@TobiasKeitsch  - Thank you for engaging with the community here for the docs.

I know the product teams are always looking for user feedback and feature request on how to make Microsoft 365 better. They keep a close tab on user feedback and it would be awesome if you could add your voice in **[UserVoice](https://office365.uservoice.com)**.

You might find others have made a similar request that you can add to, or you can open a new one. Let us know here if you do so we can up-vote your request.

Thank you for your contribution to make the docs better! Much appreciated!
